language: java
sudo: required
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
services:
  - docker
before_install:
- pwd
- docker build -t silly-content-nginx .
- docker run --rm --name some-nginx -d -p 8080:80 silly-content-nginx
